### PR TITLE
Enumerable Methods - Our own version

### PR DESCRIPTION
**Pull request by tadeuasarro**
### Ruby Enumerable from scratch

The main objective of this feature is to include some of the Enumerable native methods, from Ruby, made from scratch by us.

###### my_inject

### CODE REVIEW

**Comment by sumancrest0001** [comment]
**Status: Requires Changes :gear: 
Hello Team,** You have done a nice job to create these custom enumerable methods. Some of the test cases are passing but we have to cover different scenarios to make them similar to the default methods. You can follow [this](https://ruby-doc.org/core-2.6.5/Enumerable.html) documentation if you need to understand more about behavior of default enumerable methods.

Let's consider the following test cases and make the necessary changes.
**#my_each and #my_each_with_index**
- When a block is given
- consider hash and range also instead of just array.

**#my_select**
- returns an array containing all elements of enum for which the given block returns a true value::range
-  returns an enumerator if no block is given
- returns false if the block returns false or nil::range

**#my_all?**
- consider a case when a block or argument is not given.
- when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
- when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- when a class is passed as an argument returns false if any of the collection is not a member of such class
- consider a case when Regex is passed as an argument

**#my_any? and #my_none?**
- test the method with range.
- test without a block or argument.
- when a class is passed as an argument
  consider something like this :point_down: 
  ```
words =  %w[dog door rod blade]
  p words.my_any?(Integer)
- test the method with Regex as an argument

**#my_count**

- returns the number of items in enum through enumeration::range
 for example range.my_count

**#my_map**
- returns a new array with the results of running a given block once for every element in enum::range
- returns an Enumerator if no block is given
- test the method with a block and with or without an initial value
- when a symbol is specified with and without an initial value




```

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
**Consider the failing test cases and make the necessary changes in your methods.
All the best with the next review.
If you need any help or support, feel free to message me (Suman Shrestha) on slack.
Happy coding !!!**

**Review by lucasmazo32 — CHANGES_REQUESTED** [review]
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved kindly implement these changes:

## Required changes:

- [ ] Methods #my_all?, #my_any?, #my_inject, and #my_none should accept a range as an argument. eg: `(0...10).my_all? { |a| a < 10 }`.

- [ ] Method #my_inject should accept a symbol. eg: `array.my_inject(:+)` or `array.my_inject(:*)`.

### Happy coding! :computer:

## Lucas Mazo****

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team. 👋

**Really nice work on this so far. 👌**

However, let's fix this:

- [ ] You failed to add the `multiply_els` method as indicated in this ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/multiply_els.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2)). Kiindly include it.

- [ ] IMPORTANT - Sorry this wasn't mentioned in previous reviews but you are expected to branch out from the develop branch so please include the Github actions workflow folder that exists on the development branch.

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by krys2fa** [comment]
# Status: Project Approved! 🥇 
Congratulations team on making all the requested changes and getting this project approved. 👍 

You can now merge this branch into the master branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

All the best team,
Chris

**Pull request merged**
